
version: '2'
networks:
  our_net:
services:

  orderer.orderer.com:
    container_name: orderer.orderer.com
    image: hyperledger/fabric-orderer:1.4.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/orderer.com/orderers/orderer.orderer.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
    networks:
      - our_net

  couchdb0.org1:
    container_name: couchdb0.org1
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - our_net

  peer0.org1.orderer.com:
    image: hyperledger/fabric-peer:1.4.4
    container_name: peer0.org1.orderer.com
    environment:
      - CORE_PEER_ID=peer0.org1.orderer.com
      - CORE_PEER_ADDRESS=peer0.org1.orderer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.orderer.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_our_net
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.orderer.com/peers/peer0.org1.orderer.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
    networks:
      - our_net
    depends_on:
      - couchdb0.org1

  peer0.org2.orderer.com:
    image: hyperledger/fabric-peer:1.4.4
    container_name: peer0.org2.orderer.com
    environment:
      - CORE_PEER_ID=peer0.org2.orderer.com
      - CORE_PEER_ADDRESS=peer0.org2.orderer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.orderer.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_our_net
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.orderer.com/peers/peer0.org2.orderer.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051
    networks:
      - our_net

  couchdb0.org3:
    container_name: couchdb0.org3
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - our_net

  peer0.org3.orderer.com:
    image: hyperledger/fabric-peer:1.4.4
    container_name: peer0.org3.orderer.com
    environment:
      - CORE_PEER_ID=peer0.org3.orderer.com
      - CORE_PEER_ADDRESS=peer0.org3.orderer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.orderer.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_our_net
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.orderer.com/peers/peer0.org3.orderer.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
    networks:
      - our_net
    depends_on:
      - couchdb0.org3

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.orderer.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.orderer.com/users/Admin@org1.orderer.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh
    volumes:
      - /var/run:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./chaincode:/opt/gopath/src/github.com/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - our_net
